apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-mongo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_DATABASE
          value: user-service
        resources:
          requests:
            memory: 128Mi
            cpu: "0.2"
          limits:
            memory: 256Mi
            cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: user-mongo-service
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: datuits/devops-user-service:latest
          ports:
            - containerPort: 8081
          env:
          - name: SPRING_DATA_MONGODB_URI
            value: mongodb://user-mongo-service:27017/user-service
          resources:
            requests:
              memory: 256Mi
              cpu: "0.4"
            limits:
              memory: 512Mi
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: NodePort