# ArgoCD Application for MongoDB
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: HEAD
    chart: mongodb
    helm:
      parameters:
        - name: auth.enabled
          value: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
