# ArgoCD Application for user-service
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-service
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    repoURL: 'https://github.com/your-repo/your-helm-charts'
    targetRevision: HEAD
    path: user-service
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
