# name: Build Image User Service

# on:
#   workflow_call:
#     secrets:
#       DOCKER_HUB_ACCESS_TOKEN:
#         required: true

# jobs:
#   build-image:
#     name: Build and Push Docker Image
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Setup JDK 17
#         uses: actions/setup-java@v3
#         with:
#           distribution: 'corretto'
#           java-version: 17

#       - name: Login to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: datuits
#           password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

#       - name: Build the application
#         run: |
#           mvn clean
#           mvn -B package --file pom.xml

#       - name: Build and Push the docker image
#         run: |
#           docker build -t datuits/devops-user-service:latest .
#           docker push datuits/devops-user-service:latest