name: Create Pull Request from dev to test

on:
  push:
    branches:
      - dev

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          base: test
          head: dev
          title: "Sync dev to test"
          body: "This is an automated pull request to sync changes from dev to test."
          draft: false
