name: Deploy to Minikube

on:
  push:
    branches:
      - dev

jobs:
  example:
    name: Example Minikube-Kubernetes Cluster interaction
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.11.0
        with:
          minikube version: 'v1.33.0'
          kubernetes version: 'v1.30.0'
          github token: ${{ secrets.GITHUB_TOKEN }}
      - name: Interact with the cluster
        run: kubectl get nodes
      
      - name: Deploy K8S
          run: |
            kubectl apply -f resources.yaml

      - name: Get All
          run: kubectl get all
      
      - name: minikube service
          run: minikube service user-service --url