# GitHub Actions Workflow
name: CI/CD Pipeline

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17

    - name: Build with Maven
      run: mvn clean package


  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Helm
      uses: azure/setup-helm@v1

    - name: Deploy to Kubernetes
      run: |
        helm repo add bitnami https://charts.bitnami.com/bitnami
        helm upgrade --install my-mongo bitnami/mongodb
        helm upgrade --install user-service ./user-service --set image.repository=datuits/devops-user-service,image.tag=latest
