name: Continuous Integration for User Service

on:
  push:
    branches:
      - production

jobs:
  testing:
    name: Testing User Service
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Set up MongoDB URI
        run: echo "SPRING_DATA_MONGODB_URI=mongodb://localhost:27017/user-service" >> $GITHUB_ENV

      - name: Unit Tests
        run: mvn -B test --file pom.xml

 