name: Continuous Integration for User Service

on:
  push:
    branches:
      - dev

jobs:
  job1:
    runs-on: ubuntu-latest
    name: Build example and deploy to Minikube
    steps:
    - uses: actions/checkout@v2
    
    - name: Start Minikube
      uses: medyagh/setup-minikube@master
    
    - name: Wait for Minikube to be ready
      run: |
        while ! minikube status | grep -q "host: Running"; do
          echo "Waiting for Minikube to be ready..."
          sleep 10
        done
    
    - name: Try the cluster
      run: kubectl get pods -A
    
    - name: Deploy to Minikube
      run: |
        kubectl apply -f resources.yaml
    
    - name: Wait for resources to be ready
      run: |
        kubectl wait --for=condition=available --timeout=600s deployment/user-service
    
    - name: Test service URLs
      run: |
        kubectl get pods
        kubectl get services
        kubectl get deployments
        kubectl get all
    
    - name: Start Minikube tunnel
      run: |
        nohup minikube tunnel > /dev/null 2>&1 &
        # Wait for the tunnel to be established
        sleep 20
    
    - name: Get the service URL and test it
      run: |
        SERVICE_URL=$(minikube service user-service --url)
        echo "Service URL: $SERVICE_URL"
        echo "------------------opening the service------------------"
        # Check if the service is accessible
        RETRIES=5
        until $(curl --output /dev/null --silent --head --fail $SERVICE_URL); do
          if [ $RETRIES -le 0 ]; then
            echo "Service is not accessible at $SERVICE_URL"
            exit 1
          fi
          echo "Waiting for the service to be accessible..."
          RETRIES=$((RETRIES-1))
          sleep 10
        done
        curl $SERVICE_URL